### ISSUE TITLE
Suggestion: Concurrently run all watch targets with watch-all

### ISSUE THREAD

**Issue by sumitst05** [amitsuthar69/GoTTH#1]
It would be better to constantly watch changes for templ as well

Current `templ-generate` target:

```
.PHONY: templ-generate
templ-generate:
	templ generate
```

What it can be:

```
.PHONY: templ-generate
templ-generate:
	templ generate --watch
```

---

Finally add a `watch-all` target that can execute the 3 watch targets concurrently

```
watch-all:
	make -j 3 tailwind-watch templ-generate watch
```

**Comment by amitsuthar69** [comment]
I think `air` does watch everything concurrently, including templ templates as well. 
These are the logs when we run `air`:
```
❯ air                                                                                                                                                                                     
  __    _   ___  
 / /\  | | | |_) 
/_/--\ |_| |_| \_ v1.51.0, built with Go go1.22.2

watching .
watching cmd/api
watching cmd/web     <--- templates
watching internal/database
watching internal/server
watching static/css
watching static/script
!exclude tmp
building...
make templ-generate
make tailwind-build
(✓) Complete [ updates=2 duration=6.904305ms ]

cmd/web/base_templ.go has changed
Rebuilding...

Done in 666ms.
running...
```

**Comment by sumitst05** [comment]
> I think `air` does watch everything concurrently, including templ templates as well. These are the logs when we run `air`:
> 
> ```
> ❯ air                                                                                                                                                                                     
>   __    _   ___  
>  / /\  | | | |_) 
> /_/--\ |_| |_| \_ v1.51.0, built with Go go1.22.2
> 
> watching .
> watching cmd/api
> watching cmd/web     <--- templates
> watching internal/database
> watching internal/server
> watching static/css
> watching static/script
> !exclude tmp
> building...
> make templ-generate
> make tailwind-build
> (✓) Complete [ updates=2 duration=6.904305ms ]
> 
> cmd/web/base_templ.go has changed
> Rebuilding...
> 
> Done in 666ms.
> running...
> ```

It won't generate the template's equivalent go code tho
Same goes for tailwind
